services:
  mongo_seguro:
    image: mongo:latest
    container_name: mongo_seguro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: suasenha123
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - rede_mongo_fixa

# AQUI ESTÁ A CORREÇÃO (O PULO DO GATO):
networks:
  rede_mongo_fixa:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
